brand:
  name: Yvonne & Alan
menu-string: Menu

nav:
  - title: Schedule
    url: '#schedule'
  - title: Location
    url: '#locations'
  - title: Travel/Accomodation
    url: '#travel'
  - title: RSVP
    url: '#contact'

copyright: Copyright &copy; Yvonne and Alan 2018

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
